### ISSUE TITLE
Error: 'cloneElement' is not exported by node_modules/react/index.js

### ISSUE THREAD

**Issue by matildepark** [urbit/indigo-react#30]
## Reproduction steps

1. Go to [urbit/pkg/interface/chat](https://github.com/urbit/urbit/tree/master/pkg/interface/chat) and prepare to build the interface (specifying your pier in `urbit/pkg/interface/urbitrc`).

2. Install indigo-react and its dependencies.

```
npm install --save indigo-react
npm install --save styled-components @reach/menu-button
npm install --save indigo-tokens
```

3. Import as specified in the example to any given component. You don't even have to use them yet, just add them to the top.

```
import { H1 } from 'indigo-react';
import theme from 'indigo-tokens';
import styled, { ThemeProvider, createGlobalStyle } from 'styled-components';
```

4. `gulp watch`

## Expected behaviour

No actual changes to the current, functional build.

## Actual behaviour

Rollup can't compile the build and the files copied to my pier say I can't use import outside a mobile ([uncompiled JS](https://stackoverflow.com/questions/58211880/uncaught-syntaxerror-cannot-use-import-statement-outside-a-module-when-import)?). Rollup error log:

```
{ Error: 'cloneElement' is not exported by node_modules/react/index.js
    at error (/Users/matilde/git/urbit/pkg/interface/chat/node_modules/rollup/dist/rollup.js:10149:30)
    at Module.error (/Users/matilde/git/urbit/pkg/interface/chat/node_modules/rollup/dist/rollup.js:14132:9)
    at handleMissingExport (/Users/matilde/git/urbit/pkg/interface/chat/node_modules/rollup/dist/rollup.js:14051:21)
    at Module.traceVariable (/Users/matilde/git/urbit/pkg/interface/chat/node_modules/rollup/dist/rollup.js:14443:17)
    at ModuleScope.findVariable (/Users/matilde/git/urbit/pkg/interface/chat/node_modules/rollup/dist/rollup.js:13141:39)
    at FunctionScope.findVariable (/Users/matilde/git/urbit/pkg/interface/chat/node_modules/rollup/dist/rollup.js:2981:38)
    at ChildScope.findVariable (/Users/matilde/git/urbit/pkg/interface/chat/node_modules/rollup/dist/rollup.js:2981:38)
    at FunctionScope.findVariable (/Users/matilde/git/urbit/pkg/interface/chat/node_modules/rollup/dist/rollup.js:2981:38)
    at ChildScope.findVariable (/Users/matilde/git/urbit/pkg/interface/chat/node_modules/rollup/dist/rollup.js:2981:38)
    at FunctionScope.findVariable (/Users/matilde/git/urbit/pkg/interface/chat/node_modules/rollup/dist/rollup.js:2981:38)
  code: 'MISSING_EXPORT',
  url:
   'https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module',
  pos: 211,
  loc:
   { column: 16,
     file:
      '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/styled-components/dist/styled-components.esm.js',
     line: 3 },
  frame:
   "1: import Stylis from 'stylis/stylis.min';\n2: import _insertRulePlugin from 'stylis-rule-sheet';\n3: import React, { cloneElement, createContext, Component, createElement } from 'react';\n                   ^\n4: import unitless from '@emotion/unitless';\n5: import { isElement, isValidElementType, ForwardRef } from 'react-is';",
  watchFiles:
   [ '/Users/matilde/git/urbit/pkg/interface/chat/dist/index.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/components/root.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/api.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/store.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/subscription.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/lib/util.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/reducers/chat-update.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/reducers/initial.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/reducers/group-update.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/reducers/invite-update.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/reducers/permission-update.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/components/skeleton.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/components/sidebar.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/components/chat.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/components/settings.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/components/member.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/components/new.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/components/join.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/react/index.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/react-dom/index.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/components/lib/header-bar.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/components/lib/sidebar-invite.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/components/lib/sidebar-item.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/components/lib/message.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/components/lib/chat-tabbar.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/components/lib/chat-input.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/components/lib/member-element.js',
     '\u0000commonjsHelpers.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/react/cjs/react.production.min.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/react/cjs/react.development.js',
     '\u0000commonjs-proxy-/Users/matilde/git/urbit/pkg/interface/chat/node_modules/react/cjs/react.production.min.js',
     '\u0000commonjs-proxy-/Users/matilde/git/urbit/pkg/interface/chat/node_modules/react/cjs/react.development.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/components/lib/invite-element.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/react-dom/cjs/react-dom.production.min.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/react-dom/cjs/react-dom.development.js',
     '\u0000commonjs-proxy-/Users/matilde/git/urbit/pkg/interface/chat/node_modules/react-dom/cjs/react-dom.production.min.js',
     '\u0000commonjs-proxy-/Users/matilde/git/urbit/pkg/interface/chat/node_modules/react-dom/cjs/react-dom.development.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/lodash/lodash.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/urbit-ob/src/index.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/classnames/index.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/react-router-dom/esm/react-router-dom.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/components/lib/icons/icon-home.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/components/lib/icons/icon-spinner.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/components/lib/icons/sigil.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/dist/js/components/lib/icons/icon-send.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/urbit-ob/src/internal/co.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/urbit-ob/src/internal/ob.js',
     '\u0000commonjs-proxy-/Users/matilde/git/urbit/pkg/interface/chat/node_modules/urbit-ob/src/internal/co.js',
     '\u0000commonjs-proxy-/Users/matilde/git/urbit/pkg/interface/chat/node_modules/urbit-ob/src/internal/ob.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/indigo-react/dist/index.es.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/styled-components/dist/styled-components.esm.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/indigo-tokens/index.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/process-es6/browser.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/urbit-ob/src/internal/muk.js',
     '\u0000commonjs-proxy-/Users/matilde/git/urbit/pkg/interface/chat/node_modules/urbit-ob/src/internal/muk.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/moment/moment.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/mousetrap/mousetrap.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/prop-types/index.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/object-assign/index.js',
     '\u0000commonjs-proxy-/Users/matilde/git/urbit/pkg/interface/chat/node_modules/object-assign/index.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/prop-types/checkPropTypes.js',
     '\u0000commonjs-proxy-/Users/matilde/git/urbit/pkg/interface/chat/node_modules/prop-types/checkPropTypes.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/urbit-sigil-js/lib/dist/index.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/@babel/runtime/helpers/esm/inheritsLoose.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/@babel/runtime/helpers/esm/extends.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/@babel/runtime/helpers/esm/objectWithoutPropertiesLoose.js',
     '\u0000commonjs-proxy-/Users/matilde/git/urbit/pkg/interface/chat/node_modules/react/index.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/buffer-es6/index.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/react-router/esm/react-router.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/tiny-warning/dist/tiny-warning.esm.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/history/esm/history.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/tiny-invariant/dist/tiny-invariant.esm.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/rollup-plugin-node-globals/src/global.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/prop-types/factoryWithTypeCheckers.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/prop-types/factoryWithThrowingShims.js',
     '\u0000commonjs-proxy-/Users/matilde/git/urbit/pkg/interface/chat/node_modules/prop-types/factoryWithTypeCheckers.js',
     '\u0000commonjs-proxy-/Users/matilde/git/urbit/pkg/interface/chat/node_modules/prop-types/factoryWithThrowingShims.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/bn.js/lib/bn.js',
     '\u0000commonjs-proxy-/Users/matilde/git/urbit/pkg/interface/chat/node_modules/bn.js/lib/bn.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/prop-types/lib/ReactPropTypesSecret.js',
     '\u0000commonjs-proxy-/Users/matilde/git/urbit/pkg/interface/chat/node_modules/prop-types/lib/ReactPropTypesSecret.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/lodash.chunk/index.js',
     '\u0000commonjs-proxy-/Users/matilde/git/urbit/pkg/interface/chat/node_modules/lodash.chunk/index.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/lodash.isequal/index.js',
     '\u0000commonjs-proxy-/Users/matilde/git/urbit/pkg/interface/chat/node_modules/lodash.isequal/index.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/@reach/menu-button/es/index.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/buffer-es6/base64.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/buffer-es6/ieee754.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/buffer-es6/isArray.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/scheduler/index.js',
     '\u0000commonjs-proxy-/Users/matilde/git/urbit/pkg/interface/chat/node_modules/scheduler/index.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/react-is/index.js',
     '\u0000commonjs-proxy-/Users/matilde/git/urbit/pkg/interface/chat/node_modules/react-is/index.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/scheduler/cjs/scheduler.production.min.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/scheduler/cjs/scheduler.development.js',
     '\u0000commonjs-proxy-/Users/matilde/git/urbit/pkg/interface/chat/node_modules/scheduler/cjs/scheduler.production.min.js',
     '\u0000commonjs-proxy-/Users/matilde/git/urbit/pkg/interface/chat/node_modules/scheduler/cjs/scheduler.development.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/react-is/cjs/react-is.production.min.js',
     '/Users/matilde/git/urbit/pkg/interface/chat/node_modules/react-is/cjs/react-is.development.js',
     '\u0000commonjs-proxy-/Users/matilde/git/urbit/pkg/interface/chat/node_modules/react-is/cjs/react-is.production.min.js',
     ... 30 more items ],
  message:
   "'cloneElement' is not exported by node_modules/react/index.js",
  name: 'Error',
  stack:
   "Error: 'cloneElement' is not exported by node_modules/react/index.js\n    at error (/Users/matilde/git/urbit/pkg/interface/chat/node_modules/rollup/dist/rollup.js:10149:30)\n    at Module.error (/Users/matilde/git/urbit/pkg/interface/chat/node_modules/rollup/dist/rollup.js:14132:9)\n    at handleMissingExport (/Users/matilde/git/urbit/pkg/interface/chat/node_modules/rollup/dist/rollup.js:14051:21)\n    at Module.traceVariable (/Users/matilde/git/urbit/pkg/interface/chat/node_modules/rollup/dist/rollup.js:14443:17)\n    at ModuleScope.findVariable (/Users/matilde/git/urbit/pkg/interface/chat/node_modules/rollup/dist/rollup.js:13141:39)\n    at FunctionScope.findVariable (/Users/matilde/git/urbit/pkg/interface/chat/node_modules/rollup/dist/rollup.js:2981:38)\n    at ChildScope.findVariable (/Users/matilde/git/urbit/pkg/interface/chat/node_modules/rollup/dist/rollup.js:2981:38)\n    at FunctionScope.findVariable (/Users/matilde/git/urbit/pkg/interface/chat/node_modules/rollup/dist/rollup.js:2981:38)\n    at ChildScope.findVariable (/Users/matilde/git/urbit/pkg/interface/chat/node_modules/rollup/dist/rollup.js:2981:38)\n    at FunctionScope.findVariable (/Users/matilde/git/urbit/pkg/interface/chat/node_modules/rollup/dist/rollup.js:2981:38)",
  __safety: undefined,
  _stack: undefined,
  plugin: 'gulp-better-rollup',
  showProperties: true,
  showStack: false }
```

**Comment by nickbytes** [comment]
@matildepark Thanks for the detailed error report. We were having trouble with this before, and I think we nailed down that there were some sucrase/babel differences that were causing it, but I'm not that familiar with sucrase.

Your error makes it seem more and more like it's just a configuration issue.

This issue seems pretty promising: https://github.com/styled-components/styled-components/issues/1654#issuecomment-441151140

We've already got a similar list of `namedExports` in our gulpfile [here](https://github.com/urbit/urbit/blob/master/pkg/interface/chat/gulpfile.js#L58) and [here](https://github.com/urbit/urbit/blob/master/pkg/interface/chat/gulpfile.js#L85). Wondering if adding `cloneElement` (and probably others) will fix our issues. Any idea?

Happy to test this out, may ping you for some help building the interface.

**Comment by matildepark** [comment]
Nick,

You were spot on. Had to amend my namedExports to the following:

```
namedExports: {
'node_modules/react/index.js': ['Component', 'cloneElement', 'createContext', 'createElement', 'useState', 'useRef', 'useLayoutEffect', 'useMemo', 'useEffect', 'forwardRef', 'useContext', 'Children' ],
'node_modules/react-is/index.js': [ 'isValidElementType', 'isElement', 'ForwardRef' ],
'node_modules/react-dom/index.js': [ 'createPortal' ]
}
```

And it seemingly builds. I’ll patch this so we know. Also will start to use indigo-react components where possible, but the work on this project is most of the way done.
